# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 307afd7e8b0aca090d3cf03aebae1f9eb1d9fd5de4f313f1bcf383fcb3acd70feff7820aa5781008dcc481d6b0ddf067195ad6148d910618cda5d0eb42c5c9c4

test:
  secret_key_base: 5487c203d81345d108500a61c5a1f839a6646d76f63ea548e7b55d849df512c3dcc463ed3bbd2aeac121f3b03fa9470548f8b57b26f366282b34b3ec8d718527

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
